parameters:

    payu.manager.class: "PaymentSuite\\PayuBundle\\Services\\PayuManager"
    payu.visanet.controller.route.execute.name: "payu_visanet_execute"
    payu.visanet.routes.loader.class: "PaymentSuite\\PayuBundle\\Router\\VisanetRoutesLoader"
    payu.factory.payurequest.class: "PaymentSuite\\PayuBundle\\Factory\\PayuRequestFactory"
    payu.factory.payutransaction.class: "PaymentSuite\\PayuBundle\\Factory\\PayuTransactionFactory"
    payu.factory.merchant.class: "PaymentSuite\\PayuBundle\\Factory\\MerchantFactory"
    payu.factory.order.class: "PaymentSuite\\PayuBundle\\Factory\\OrderFactory"